version: '3.8'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=db_test
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=pass123
